apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatserver
  namespace: go
  labels:
    app: chatserver
    version: v1
spec:
  replicas: 2
  minReadySeconds: 10 
  selector:
    matchLabels:
      app: chatserver
      version: v1
  template:
    metadata:
      labels:
        app: chatserver
        version: v1
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: chatserver
        image: hermanyep/chatserver
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      hostAliases:
      - hostnames:    
        - kafka-0.kafka-headless.kafka.svc.cluster.local
        ip: 10.101.110.38
---
apiVersion: v1 
kind: Service 
metadata:
  name: chatserver
  namespace: go
  labels:
    app: chatserver
    version: v1
spec:
  ports:
    - port: 8080 
      targetPort: 8080 
      name: grpc-port
      protocol: TCP
  selector:
    app: chatserver


---
apiVersion: networking.k8s.io/v1  
kind: Ingress    
metadata:           
  name: chatserver
  namespace: go
  annotations:            
    kubernetes.io/ingress.class: nginx  
    nginx.ingress.kubernetes.io/configuration-snippet: |
       proxy_set_header Upgrade "websocket";
       proxy_set_header Connection "Upgrade";
spec:      
  rules: 
  - host: chatserver.go.com
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: chatserver
            port: 
              number: 8080
